# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0215012aea99f5a96bc1fc615f2ac9a88aac71327757b8d9841d98ff8244de1cd5e278bf35383c481c15fb83bb54501065dbed5e092b2260a0d2130f744ceb62

test:
  secret_key_base: 827bcbbd97ab3703782ea206903181cdb7893d101de087020c1f1d9198e642326eaecf357bfb169a0b97ffc58346df010448a508fd274e78ff809db3250ed632

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
